version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - main_db

  main_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - main_db

  main_db:
    image: mysql:8.0.26
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_ROOT_PASSWORD: main
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306